% Code taken from lab-PM.
included(X) :- node(X), not excluded(X).
excluded(X) :- node(X), not included(X).

equal(X,X) :- node(X).

three_or_more :-
        included(X),
        included(Y),
        included(Z),
        not equal(X, Y),
        not equal(Y, Z),
        not equal(X, Z).

:- not three_or_more.

% If nodes X and Y are in the graph and are not
% eqaul there has to be an edge between them.
:- included(X), included(Y), not edge(X, Y), not equal(X, Y).